### ISSUE TITLE
Appointments page is accessible even without being logged in 

### ISSUE THREAD

**Issue by junaed1995** [bisho1995/join-us-design-lab#16]
When opening the platform and clicking on appointments, it is accessible even when not logged in.
Step-1
Open the home page http://localhost:3000/
Step-2
Click on "Client Dashboard", http://localhost:3000/client-dashboard . 
Step-3
Click on "Appointments", http://localhost:3000/client-dashboard . "Appointments"(http://localhost:3000/client-dashboard/appointments) opens without being logged in.

**Comment by bisho1995** [comment]
fixed

**Comment by arnabnandy1996** [comment]
Now not possible without login as present login and logout button both present.
