### ISSUE TITLE
More fields required in Client register page.

### ISSUE THREAD

**Issue by junaed1995** [bisho1995/join-us-design-lab#18]
DOB, Phone number, Address & Gender fields required.
Step-1
Open the home page(http://localhost:3000/).
Step-2
Click on "Register Client".(http://localhost:3000/register).

Only fields Full Name, Email id, password and confirm password present. DOB(Date of birth), Phone number,Address and Gender fields required to be added into the register page.

**Comment by bisho1995** [comment]
Cannot do due to constraint of time
