### ISSUE TITLE
"successfully registered" is to be shown

### ISSUE THREAD

**Issue by junaed1995** [bisho1995/join-us-design-lab#19]
"successfully registered" is to be shown in place of  "Account has been successfully created" after account creation.
Step-1
Open the home page http://localhost:3000/
Step-2
Click on Register Client. http://localhost:3000/register
Step-3 
Provide valid email and password for registration. 

On successful account creation, "successfully registered" is to be shown in place of  "Account has been successfully created".

**Comment by arnabnandy1996** [comment]
instead of showing "Account has been successfully created", now  "successfully registered" is showing.

**Comment by bisho1995** [comment]
@arnabnandy1996  please post your code which you changed to close this issue.

**Comment by arnabnandy1996** [comment]
winston.info(data);
                res.send('successfully registered');
            })
