### ISSUE TITLE
Logout button needed.

### ISSUE THREAD

**Issue by junaed1995** [bisho1995/join-us-design-lab#20]
After successful account creation, the user logged in.However, even after the session, the client closes the window. Later on, even after opening the login in the page it logs in automatically. Thus a logout button is needed.
Step-1
Open the homepage http://localhost:3000/
Step-2
Click on the login page, http://localhost:3000/login.
Step-3
Close the window and exit
Step-4
Repeat steps 1 to 2.

Automatically logs in. Thus a log button is needed.

**Comment by bisho1995** [comment]
Done
