### ISSUE TITLE
Short Passwords (less than 8 characters)should not be accepted

### ISSUE THREAD

**Issue by junaed1995** [bisho1995/join-us-design-lab#21]
Password less than 8 characters are not to be accepted.
Step-1
Open the home page http://localhost:3000/
Step-2
Click on register client. http://localhost:3000/register
Step-3 
Enter a password less than 8 characters.

Password less than 8 characters are getting accepted.

**Comment by bisho1995** [comment]
Fixed

**Comment by bisho1995** [comment]
/**
 * Issue #21, #22, #23
 * Added validation to check for
 * password length
 * passwords match
 */
const expressValidator = [
    check('email')
        .isEmail()
        .withMessage('must be an email'),
    check('password', 'Not a valid password')
        .isLength({min:8, max: 25})
        .exists(),
    check('confirm_password', 'Confirm password doesnot match password')
        .isLength({min:8, max: 25})
        .exists()
        .custom((value, { req }) => {
            return value === req.body.password
		}),
	check('start_time', 'The start time and the end time has to be within 0 and 24')
		.exists().
		custom(value=>{
			return value >= 0 && value <= 24
		}),
	check('end_time', 'The end time and the end time has to be within 0 and 24')
		.exists()
		.custom(value=>{
			return value >= 0 && value <= 24
		})
]
