### ISSUE TITLE
Confirm password for Register Client not working

### ISSUE THREAD

**Issue by junaed1995** [bisho1995/join-us-design-lab#22]
Upon not entering the same password in confirm password field the registration shows successful. 
Step1
Open the home page http://localhost:3000/
Step2
Click on register client. http://localhost:3000/register
Step3
Enter a password.
Step4
Enter a different password in confirm password field.

The account is successfully created.

**Comment by bisho1995** [comment]
Fixed

**Comment by bisho1995** [comment]
/**
 * Issue #21, #22, #23
 * Added validation to check for
 * password length
 * passwords match
 */
const expressValidator = [
    check('email')
        .isEmail()
        .withMessage('must be an email'),
    check('password', 'Not a valid password')
        .isLength({min:8, max: 25})
        .exists(),
    check('confirm_password', 'Confirm password doesnot match password')
        .isLength({min:8, max: 25})
        .exists()
        .custom((value, { req }) => {
            return value === req.body.password
		}),
	check('start_time', 'The start time and the end time has to be within 0 and 24')
		.exists().
		custom(value=>{
			return value >= 0 && value <= 24
		}),
	check('end_time', 'The end time and the end time has to be within 0 and 24')
		.exists()
		.custom(value=>{
			return value >= 0 && value <= 24
		})
]
