### ISSUE TITLE
Can log in/sign up even with email which does not exist for both PM account as well as Client

### ISSUE THREAD

**Issue by junaed1995** [bisho1995/join-us-design-lab#26]
Step1:
Open the home page http://localhost:3000/.
Step 2:
Click on log in button.
Step 3:
Enter email which does not exist with a password.
Step 4:
User logged in / user account successfully  created (in case of sign up).

**Comment by bisho1995** [comment]
User cannot sign in with an email which is not registered in the system. However for while registering to check if an email is actually valid or not we must put the feature of verifying email addresses which cannot be done now due to constraints of time.
